---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18

platforms:
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[flash_test]
    attributes:
      flash:
        trust:
          - '# trust home directory'
          - C:\Users\vagrant
        mms_cfg:
          AutoUpdateDisable: 0
          SilentAutoUpdateEnable: 1
